//! Addresses for CSRs. Automatically generated by parse_opcodes.
//!
//! As the CSRs are implemented the `#[allow(unused)] around the respective
//! index should be removed.
#[allow(unused)]
pub const CSR_FFLAGS: u16 = 0x1;
#[allow(unused)]
pub const CSR_FRM: u16 = 0x2;
#[allow(unused)]
pub const CSR_FCSR: u16 = 0x3;
#[allow(unused)]
pub const CSR_VSTART: u16 = 0x8;
#[allow(unused)]
pub const CSR_VXSAT: u16 = 0x9;
#[allow(unused)]
pub const CSR_VXRM: u16 = 0xa;
#[allow(unused)]
pub const CSR_VCSR: u16 = 0xf;
#[allow(unused)]
pub const CSR_SEED: u16 = 0x15;
#[allow(unused)]
pub const CSR_CYCLE: u16 = 0xc00;
#[allow(unused)]
pub const CSR_TIME: u16 = 0xc01;
#[allow(unused)]
pub const CSR_INSTRET: u16 = 0xc02;
#[allow(unused)]
pub const CSR_HPMCOUNTER3: u16 = 0xc03;
#[allow(unused)]
pub const CSR_HPMCOUNTER4: u16 = 0xc04;
#[allow(unused)]
pub const CSR_HPMCOUNTER5: u16 = 0xc05;
#[allow(unused)]
pub const CSR_HPMCOUNTER6: u16 = 0xc06;
#[allow(unused)]
pub const CSR_HPMCOUNTER7: u16 = 0xc07;
#[allow(unused)]
pub const CSR_HPMCOUNTER8: u16 = 0xc08;
#[allow(unused)]
pub const CSR_HPMCOUNTER9: u16 = 0xc09;
#[allow(unused)]
pub const CSR_HPMCOUNTER10: u16 = 0xc0a;
#[allow(unused)]
pub const CSR_HPMCOUNTER11: u16 = 0xc0b;
#[allow(unused)]
pub const CSR_HPMCOUNTER12: u16 = 0xc0c;
#[allow(unused)]
pub const CSR_HPMCOUNTER13: u16 = 0xc0d;
#[allow(unused)]
pub const CSR_HPMCOUNTER14: u16 = 0xc0e;
#[allow(unused)]
pub const CSR_HPMCOUNTER15: u16 = 0xc0f;
#[allow(unused)]
pub const CSR_HPMCOUNTER16: u16 = 0xc10;
#[allow(unused)]
pub const CSR_HPMCOUNTER17: u16 = 0xc11;
#[allow(unused)]
pub const CSR_HPMCOUNTER18: u16 = 0xc12;
#[allow(unused)]
pub const CSR_HPMCOUNTER19: u16 = 0xc13;
#[allow(unused)]
pub const CSR_HPMCOUNTER20: u16 = 0xc14;
#[allow(unused)]
pub const CSR_HPMCOUNTER21: u16 = 0xc15;
#[allow(unused)]
pub const CSR_HPMCOUNTER22: u16 = 0xc16;
#[allow(unused)]
pub const CSR_HPMCOUNTER23: u16 = 0xc17;
#[allow(unused)]
pub const CSR_HPMCOUNTER24: u16 = 0xc18;
#[allow(unused)]
pub const CSR_HPMCOUNTER25: u16 = 0xc19;
#[allow(unused)]
pub const CSR_HPMCOUNTER26: u16 = 0xc1a;
#[allow(unused)]
pub const CSR_HPMCOUNTER27: u16 = 0xc1b;
#[allow(unused)]
pub const CSR_HPMCOUNTER28: u16 = 0xc1c;
#[allow(unused)]
pub const CSR_HPMCOUNTER29: u16 = 0xc1d;
#[allow(unused)]
pub const CSR_HPMCOUNTER30: u16 = 0xc1e;
#[allow(unused)]
pub const CSR_HPMCOUNTER31: u16 = 0xc1f;
#[allow(unused)]
pub const CSR_VL: u16 = 0xc20;
#[allow(unused)]
pub const CSR_VTYPE: u16 = 0xc21;
#[allow(unused)]
pub const CSR_VLENB: u16 = 0xc22;
#[allow(unused)]
pub const CSR_SSTATUS: u16 = 0x100;
#[allow(unused)]
pub const CSR_SEDELEG: u16 = 0x102;
#[allow(unused)]
pub const CSR_SIDELEG: u16 = 0x103;
#[allow(unused)]
pub const CSR_SIE: u16 = 0x104;
#[allow(unused)]
pub const CSR_STVEC: u16 = 0x105;
#[allow(unused)]
pub const CSR_SCOUNTEREN: u16 = 0x106;
#[allow(unused)]
pub const CSR_SENVCFG: u16 = 0x10a;
#[allow(unused)]
pub const CSR_SSCRATCH: u16 = 0x140;
#[allow(unused)]
pub const CSR_SEPC: u16 = 0x141;
#[allow(unused)]
pub const CSR_SCAUSE: u16 = 0x142;
#[allow(unused)]
pub const CSR_STVAL: u16 = 0x143;
#[allow(unused)]
pub const CSR_SIP: u16 = 0x144;
#[allow(unused)]
pub const CSR_SATP: u16 = 0x180;
#[allow(unused)]
pub const CSR_SCONTEXT: u16 = 0x5a8;
#[allow(unused)]
pub const CSR_VSSTATUS: u16 = 0x200;
#[allow(unused)]
pub const CSR_VSIE: u16 = 0x204;
#[allow(unused)]
pub const CSR_VSTVEC: u16 = 0x205;
#[allow(unused)]
pub const CSR_VSSCRATCH: u16 = 0x240;
#[allow(unused)]
pub const CSR_VSEPC: u16 = 0x241;
#[allow(unused)]
pub const CSR_VSCAUSE: u16 = 0x242;
#[allow(unused)]
pub const CSR_VSTVAL: u16 = 0x243;
#[allow(unused)]
pub const CSR_VSIP: u16 = 0x244;
#[allow(unused)]
pub const CSR_VSATP: u16 = 0x280;
#[allow(unused)]
pub const CSR_HSTATUS: u16 = 0x600;
#[allow(unused)]
pub const CSR_HEDELEG: u16 = 0x602;
#[allow(unused)]
pub const CSR_HIDELEG: u16 = 0x603;
#[allow(unused)]
pub const CSR_HIE: u16 = 0x604;
#[allow(unused)]
pub const CSR_HTIMEDELTA: u16 = 0x605;
#[allow(unused)]
pub const CSR_HCOUNTEREN: u16 = 0x606;
#[allow(unused)]
pub const CSR_HGEIE: u16 = 0x607;
#[allow(unused)]
pub const CSR_HENVCFG: u16 = 0x60a;
#[allow(unused)]
pub const CSR_HTVAL: u16 = 0x643;
#[allow(unused)]
pub const CSR_HIP: u16 = 0x644;
#[allow(unused)]
pub const CSR_HVIP: u16 = 0x645;
#[allow(unused)]
pub const CSR_HTINST: u16 = 0x64a;
#[allow(unused)]
pub const CSR_HGATP: u16 = 0x680;
#[allow(unused)]
pub const CSR_HCONTEXT: u16 = 0x6a8;
#[allow(unused)]
pub const CSR_HGEIP: u16 = 0xe12;
#[allow(unused)]
pub const CSR_UTVT: u16 = 0x7;
#[allow(unused)]
pub const CSR_UNXTI: u16 = 0x45;
#[allow(unused)]
pub const CSR_UINTSTATUS: u16 = 0x46;
#[allow(unused)]
pub const CSR_USCRATCHCSW: u16 = 0x48;
#[allow(unused)]
pub const CSR_USCRATCHCSWL: u16 = 0x49;
#[allow(unused)]
pub const CSR_STVT: u16 = 0x107;
#[allow(unused)]
pub const CSR_SNXTI: u16 = 0x145;
#[allow(unused)]
pub const CSR_SINTSTATUS: u16 = 0x146;
#[allow(unused)]
pub const CSR_SSCRATCHCSW: u16 = 0x148;
#[allow(unused)]
pub const CSR_SSCRATCHCSWL: u16 = 0x149;
#[allow(unused)]
pub const CSR_MTVT: u16 = 0x307;
#[allow(unused)]
pub const CSR_MNXTI: u16 = 0x345;
#[allow(unused)]
pub const CSR_MINTSTATUS: u16 = 0x346;
#[allow(unused)]
pub const CSR_MSCRATCHCSW: u16 = 0x348;
#[allow(unused)]
pub const CSR_MSCRATCHCSWL: u16 = 0x349;
#[allow(unused)]
pub const CSR_MSTATUS: u16 = 0x300;
#[allow(unused)]
pub const CSR_MISA: u16 = 0x301;
#[allow(unused)]
pub const CSR_MEDELEG: u16 = 0x302;
#[allow(unused)]
pub const CSR_MIDELEG: u16 = 0x303;
#[allow(unused)]
pub const CSR_MIE: u16 = 0x304;
#[allow(unused)]
pub const CSR_MTVEC: u16 = 0x305;
#[allow(unused)]
pub const CSR_MCOUNTEREN: u16 = 0x306;
#[allow(unused)]
pub const CSR_MENVCFG: u16 = 0x30a;
#[allow(unused)]
pub const CSR_MCOUNTINHIBIT: u16 = 0x320;
#[allow(unused)]
pub const CSR_MSCRATCH: u16 = 0x340;
#[allow(unused)]
pub const CSR_MEPC: u16 = 0x341;
pub const CSR_MCAUSE: u16 = 0x342;
#[allow(unused)]
pub const CSR_MTVAL: u16 = 0x343;
#[allow(unused)]
pub const CSR_MIP: u16 = 0x344;
#[allow(unused)]
pub const CSR_MTINST: u16 = 0x34a;
#[allow(unused)]
pub const CSR_MTVAL2: u16 = 0x34b;
#[allow(unused)]
pub const CSR_PMPCFG0: u16 = 0x3a0;
#[allow(unused)]
pub const CSR_PMPCFG1: u16 = 0x3a1;
#[allow(unused)]
pub const CSR_PMPCFG2: u16 = 0x3a2;
#[allow(unused)]
pub const CSR_PMPCFG3: u16 = 0x3a3;
#[allow(unused)]
pub const CSR_PMPCFG4: u16 = 0x3a4;
#[allow(unused)]
pub const CSR_PMPCFG5: u16 = 0x3a5;
#[allow(unused)]
pub const CSR_PMPCFG6: u16 = 0x3a6;
#[allow(unused)]
pub const CSR_PMPCFG7: u16 = 0x3a7;
#[allow(unused)]
pub const CSR_PMPCFG8: u16 = 0x3a8;
#[allow(unused)]
pub const CSR_PMPCFG9: u16 = 0x3a9;
#[allow(unused)]
pub const CSR_PMPCFG10: u16 = 0x3aa;
#[allow(unused)]
pub const CSR_PMPCFG11: u16 = 0x3ab;
#[allow(unused)]
pub const CSR_PMPCFG12: u16 = 0x3ac;
#[allow(unused)]
pub const CSR_PMPCFG13: u16 = 0x3ad;
#[allow(unused)]
pub const CSR_PMPCFG14: u16 = 0x3ae;
#[allow(unused)]
pub const CSR_PMPCFG15: u16 = 0x3af;
#[allow(unused)]
pub const CSR_PMPADDR0: u16 = 0x3b0;
#[allow(unused)]
pub const CSR_PMPADDR1: u16 = 0x3b1;
#[allow(unused)]
pub const CSR_PMPADDR2: u16 = 0x3b2;
#[allow(unused)]
pub const CSR_PMPADDR3: u16 = 0x3b3;
#[allow(unused)]
pub const CSR_PMPADDR4: u16 = 0x3b4;
#[allow(unused)]
pub const CSR_PMPADDR5: u16 = 0x3b5;
#[allow(unused)]
pub const CSR_PMPADDR6: u16 = 0x3b6;
#[allow(unused)]
pub const CSR_PMPADDR7: u16 = 0x3b7;
#[allow(unused)]
pub const CSR_PMPADDR8: u16 = 0x3b8;
#[allow(unused)]
pub const CSR_PMPADDR9: u16 = 0x3b9;
#[allow(unused)]
pub const CSR_PMPADDR10: u16 = 0x3ba;
#[allow(unused)]
pub const CSR_PMPADDR11: u16 = 0x3bb;
#[allow(unused)]
pub const CSR_PMPADDR12: u16 = 0x3bc;
#[allow(unused)]
pub const CSR_PMPADDR13: u16 = 0x3bd;
#[allow(unused)]
pub const CSR_PMPADDR14: u16 = 0x3be;
#[allow(unused)]
pub const CSR_PMPADDR15: u16 = 0x3bf;
#[allow(unused)]
pub const CSR_PMPADDR16: u16 = 0x3c0;
#[allow(unused)]
pub const CSR_PMPADDR17: u16 = 0x3c1;
#[allow(unused)]
pub const CSR_PMPADDR18: u16 = 0x3c2;
#[allow(unused)]
pub const CSR_PMPADDR19: u16 = 0x3c3;
#[allow(unused)]
pub const CSR_PMPADDR20: u16 = 0x3c4;
#[allow(unused)]
pub const CSR_PMPADDR21: u16 = 0x3c5;
#[allow(unused)]
pub const CSR_PMPADDR22: u16 = 0x3c6;
#[allow(unused)]
pub const CSR_PMPADDR23: u16 = 0x3c7;
#[allow(unused)]
pub const CSR_PMPADDR24: u16 = 0x3c8;
#[allow(unused)]
pub const CSR_PMPADDR25: u16 = 0x3c9;
#[allow(unused)]
pub const CSR_PMPADDR26: u16 = 0x3ca;
#[allow(unused)]
pub const CSR_PMPADDR27: u16 = 0x3cb;
#[allow(unused)]
pub const CSR_PMPADDR28: u16 = 0x3cc;
#[allow(unused)]
pub const CSR_PMPADDR29: u16 = 0x3cd;
#[allow(unused)]
pub const CSR_PMPADDR30: u16 = 0x3ce;
#[allow(unused)]
pub const CSR_PMPADDR31: u16 = 0x3cf;
#[allow(unused)]
pub const CSR_PMPADDR32: u16 = 0x3d0;
#[allow(unused)]
pub const CSR_PMPADDR33: u16 = 0x3d1;
#[allow(unused)]
pub const CSR_PMPADDR34: u16 = 0x3d2;
#[allow(unused)]
pub const CSR_PMPADDR35: u16 = 0x3d3;
#[allow(unused)]
pub const CSR_PMPADDR36: u16 = 0x3d4;
#[allow(unused)]
pub const CSR_PMPADDR37: u16 = 0x3d5;
#[allow(unused)]
pub const CSR_PMPADDR38: u16 = 0x3d6;
#[allow(unused)]
pub const CSR_PMPADDR39: u16 = 0x3d7;
#[allow(unused)]
pub const CSR_PMPADDR40: u16 = 0x3d8;
#[allow(unused)]
pub const CSR_PMPADDR41: u16 = 0x3d9;
#[allow(unused)]
pub const CSR_PMPADDR42: u16 = 0x3da;
#[allow(unused)]
pub const CSR_PMPADDR43: u16 = 0x3db;
#[allow(unused)]
pub const CSR_PMPADDR44: u16 = 0x3dc;
#[allow(unused)]
pub const CSR_PMPADDR45: u16 = 0x3dd;
#[allow(unused)]
pub const CSR_PMPADDR46: u16 = 0x3de;
#[allow(unused)]
pub const CSR_PMPADDR47: u16 = 0x3df;
#[allow(unused)]
pub const CSR_PMPADDR48: u16 = 0x3e0;
#[allow(unused)]
pub const CSR_PMPADDR49: u16 = 0x3e1;
#[allow(unused)]
pub const CSR_PMPADDR50: u16 = 0x3e2;
#[allow(unused)]
pub const CSR_PMPADDR51: u16 = 0x3e3;
#[allow(unused)]
pub const CSR_PMPADDR52: u16 = 0x3e4;
#[allow(unused)]
pub const CSR_PMPADDR53: u16 = 0x3e5;
#[allow(unused)]
pub const CSR_PMPADDR54: u16 = 0x3e6;
#[allow(unused)]
pub const CSR_PMPADDR55: u16 = 0x3e7;
#[allow(unused)]
pub const CSR_PMPADDR56: u16 = 0x3e8;
#[allow(unused)]
pub const CSR_PMPADDR57: u16 = 0x3e9;
#[allow(unused)]
pub const CSR_PMPADDR58: u16 = 0x3ea;
#[allow(unused)]
pub const CSR_PMPADDR59: u16 = 0x3eb;
#[allow(unused)]
pub const CSR_PMPADDR60: u16 = 0x3ec;
#[allow(unused)]
pub const CSR_PMPADDR61: u16 = 0x3ed;
#[allow(unused)]
pub const CSR_PMPADDR62: u16 = 0x3ee;
#[allow(unused)]
pub const CSR_PMPADDR63: u16 = 0x3ef;
#[allow(unused)]
pub const CSR_MSECCFG: u16 = 0x747;
#[allow(unused)]
pub const CSR_TSELECT: u16 = 0x7a0;
#[allow(unused)]
pub const CSR_TDATA1: u16 = 0x7a1;
#[allow(unused)]
pub const CSR_TDATA2: u16 = 0x7a2;
#[allow(unused)]
pub const CSR_TDATA3: u16 = 0x7a3;
#[allow(unused)]
pub const CSR_TINFO: u16 = 0x7a4;
#[allow(unused)]
pub const CSR_TCONTROL: u16 = 0x7a5;
#[allow(unused)]
pub const CSR_MCONTEXT: u16 = 0x7a8;
#[allow(unused)]
pub const CSR_MSCONTEXT: u16 = 0x7aa;
#[allow(unused)]
pub const CSR_DCSR: u16 = 0x7b0;
#[allow(unused)]
pub const CSR_DPC: u16 = 0x7b1;
#[allow(unused)]
pub const CSR_DSCRATCH0: u16 = 0x7b2;
#[allow(unused)]
pub const CSR_DSCRATCH1: u16 = 0x7b3;
#[allow(unused)]
pub const CSR_MCYCLE: u16 = 0xb00;
#[allow(unused)]
pub const CSR_MINSTRET: u16 = 0xb02;
#[allow(unused)]
pub const CSR_MHPMCOUNTER3: u16 = 0xb03;
#[allow(unused)]
pub const CSR_MHPMCOUNTER4: u16 = 0xb04;
#[allow(unused)]
pub const CSR_MHPMCOUNTER5: u16 = 0xb05;
#[allow(unused)]
pub const CSR_MHPMCOUNTER6: u16 = 0xb06;
#[allow(unused)]
pub const CSR_MHPMCOUNTER7: u16 = 0xb07;
#[allow(unused)]
pub const CSR_MHPMCOUNTER8: u16 = 0xb08;
#[allow(unused)]
pub const CSR_MHPMCOUNTER9: u16 = 0xb09;
#[allow(unused)]
pub const CSR_MHPMCOUNTER10: u16 = 0xb0a;
#[allow(unused)]
pub const CSR_MHPMCOUNTER11: u16 = 0xb0b;
#[allow(unused)]
pub const CSR_MHPMCOUNTER12: u16 = 0xb0c;
#[allow(unused)]
pub const CSR_MHPMCOUNTER13: u16 = 0xb0d;
#[allow(unused)]
pub const CSR_MHPMCOUNTER14: u16 = 0xb0e;
#[allow(unused)]
pub const CSR_MHPMCOUNTER15: u16 = 0xb0f;
#[allow(unused)]
pub const CSR_MHPMCOUNTER16: u16 = 0xb10;
#[allow(unused)]
pub const CSR_MHPMCOUNTER17: u16 = 0xb11;
#[allow(unused)]
pub const CSR_MHPMCOUNTER18: u16 = 0xb12;
#[allow(unused)]
pub const CSR_MHPMCOUNTER19: u16 = 0xb13;
#[allow(unused)]
pub const CSR_MHPMCOUNTER20: u16 = 0xb14;
#[allow(unused)]
pub const CSR_MHPMCOUNTER21: u16 = 0xb15;
#[allow(unused)]
pub const CSR_MHPMCOUNTER22: u16 = 0xb16;
#[allow(unused)]
pub const CSR_MHPMCOUNTER23: u16 = 0xb17;
#[allow(unused)]
pub const CSR_MHPMCOUNTER24: u16 = 0xb18;
#[allow(unused)]
pub const CSR_MHPMCOUNTER25: u16 = 0xb19;
#[allow(unused)]
pub const CSR_MHPMCOUNTER26: u16 = 0xb1a;
#[allow(unused)]
pub const CSR_MHPMCOUNTER27: u16 = 0xb1b;
#[allow(unused)]
pub const CSR_MHPMCOUNTER28: u16 = 0xb1c;
#[allow(unused)]
pub const CSR_MHPMCOUNTER29: u16 = 0xb1d;
#[allow(unused)]
pub const CSR_MHPMCOUNTER30: u16 = 0xb1e;
#[allow(unused)]
pub const CSR_MHPMCOUNTER31: u16 = 0xb1f;
#[allow(unused)]
pub const CSR_MHPMEVENT3: u16 = 0x323;
#[allow(unused)]
pub const CSR_MHPMEVENT4: u16 = 0x324;
#[allow(unused)]
pub const CSR_MHPMEVENT5: u16 = 0x325;
#[allow(unused)]
pub const CSR_MHPMEVENT6: u16 = 0x326;
#[allow(unused)]
pub const CSR_MHPMEVENT7: u16 = 0x327;
#[allow(unused)]
pub const CSR_MHPMEVENT8: u16 = 0x328;
#[allow(unused)]
pub const CSR_MHPMEVENT9: u16 = 0x329;
#[allow(unused)]
pub const CSR_MHPMEVENT10: u16 = 0x32a;
#[allow(unused)]
pub const CSR_MHPMEVENT11: u16 = 0x32b;
#[allow(unused)]
pub const CSR_MHPMEVENT12: u16 = 0x32c;
#[allow(unused)]
pub const CSR_MHPMEVENT13: u16 = 0x32d;
#[allow(unused)]
pub const CSR_MHPMEVENT14: u16 = 0x32e;
#[allow(unused)]
pub const CSR_MHPMEVENT15: u16 = 0x32f;
#[allow(unused)]
pub const CSR_MHPMEVENT16: u16 = 0x330;
#[allow(unused)]
pub const CSR_MHPMEVENT17: u16 = 0x331;
#[allow(unused)]
pub const CSR_MHPMEVENT18: u16 = 0x332;
#[allow(unused)]
pub const CSR_MHPMEVENT19: u16 = 0x333;
#[allow(unused)]
pub const CSR_MHPMEVENT20: u16 = 0x334;
#[allow(unused)]
pub const CSR_MHPMEVENT21: u16 = 0x335;
#[allow(unused)]
pub const CSR_MHPMEVENT22: u16 = 0x336;
#[allow(unused)]
pub const CSR_MHPMEVENT23: u16 = 0x337;
#[allow(unused)]
pub const CSR_MHPMEVENT24: u16 = 0x338;
#[allow(unused)]
pub const CSR_MHPMEVENT25: u16 = 0x339;
#[allow(unused)]
pub const CSR_MHPMEVENT26: u16 = 0x33a;
#[allow(unused)]
pub const CSR_MHPMEVENT27: u16 = 0x33b;
#[allow(unused)]
pub const CSR_MHPMEVENT28: u16 = 0x33c;
#[allow(unused)]
pub const CSR_MHPMEVENT29: u16 = 0x33d;
#[allow(unused)]
pub const CSR_MHPMEVENT30: u16 = 0x33e;
#[allow(unused)]
pub const CSR_MHPMEVENT31: u16 = 0x33f;
#[allow(unused)]
pub const CSR_MVENDORID: u16 = 0xf11;
#[allow(unused)]
pub const CSR_MARCHID: u16 = 0xf12;
#[allow(unused)]
pub const CSR_MIMPID: u16 = 0xf13;
#[allow(unused)]
pub const CSR_MHARTID: u16 = 0xf14;
#[allow(unused)]
pub const CSR_MCONFIGPTR: u16 = 0xf15;
#[allow(unused)]
pub const CSR_HTIMEDELTAH: u16 = 0x615;
#[allow(unused)]
pub const CSR_HENVCFGH: u16 = 0x61a;
#[allow(unused)]
pub const CSR_CYCLEH: u16 = 0xc80;
#[allow(unused)]
pub const CSR_TIMEH: u16 = 0xc81;
#[allow(unused)]
pub const CSR_INSTRETH: u16 = 0xc82;
#[allow(unused)]
pub const CSR_HPMCOUNTER3H: u16 = 0xc83;
#[allow(unused)]
pub const CSR_HPMCOUNTER4H: u16 = 0xc84;
#[allow(unused)]
pub const CSR_HPMCOUNTER5H: u16 = 0xc85;
#[allow(unused)]
pub const CSR_HPMCOUNTER6H: u16 = 0xc86;
#[allow(unused)]
pub const CSR_HPMCOUNTER7H: u16 = 0xc87;
#[allow(unused)]
pub const CSR_HPMCOUNTER8H: u16 = 0xc88;
#[allow(unused)]
pub const CSR_HPMCOUNTER9H: u16 = 0xc89;
#[allow(unused)]
pub const CSR_HPMCOUNTER10H: u16 = 0xc8a;
#[allow(unused)]
pub const CSR_HPMCOUNTER11H: u16 = 0xc8b;
#[allow(unused)]
pub const CSR_HPMCOUNTER12H: u16 = 0xc8c;
#[allow(unused)]
pub const CSR_HPMCOUNTER13H: u16 = 0xc8d;
#[allow(unused)]
pub const CSR_HPMCOUNTER14H: u16 = 0xc8e;
#[allow(unused)]
pub const CSR_HPMCOUNTER15H: u16 = 0xc8f;
#[allow(unused)]
pub const CSR_HPMCOUNTER16H: u16 = 0xc90;
#[allow(unused)]
pub const CSR_HPMCOUNTER17H: u16 = 0xc91;
#[allow(unused)]
pub const CSR_HPMCOUNTER18H: u16 = 0xc92;
#[allow(unused)]
pub const CSR_HPMCOUNTER19H: u16 = 0xc93;
#[allow(unused)]
pub const CSR_HPMCOUNTER20H: u16 = 0xc94;
#[allow(unused)]
pub const CSR_HPMCOUNTER21H: u16 = 0xc95;
#[allow(unused)]
pub const CSR_HPMCOUNTER22H: u16 = 0xc96;
#[allow(unused)]
pub const CSR_HPMCOUNTER23H: u16 = 0xc97;
#[allow(unused)]
pub const CSR_HPMCOUNTER24H: u16 = 0xc98;
#[allow(unused)]
pub const CSR_HPMCOUNTER25H: u16 = 0xc99;
#[allow(unused)]
pub const CSR_HPMCOUNTER26H: u16 = 0xc9a;
#[allow(unused)]
pub const CSR_HPMCOUNTER27H: u16 = 0xc9b;
#[allow(unused)]
pub const CSR_HPMCOUNTER28H: u16 = 0xc9c;
#[allow(unused)]
pub const CSR_HPMCOUNTER29H: u16 = 0xc9d;
#[allow(unused)]
pub const CSR_HPMCOUNTER30H: u16 = 0xc9e;
#[allow(unused)]
pub const CSR_HPMCOUNTER31H: u16 = 0xc9f;
#[allow(unused)]
pub const CSR_MSTATUSH: u16 = 0x310;
#[allow(unused)]
pub const CSR_MENVCFGH: u16 = 0x31a;
#[allow(unused)]
pub const CSR_MSECCFGH: u16 = 0x757;
#[allow(unused)]
pub const CSR_MCYCLEH: u16 = 0xb80;
#[allow(unused)]
pub const CSR_MINSTRETH: u16 = 0xb82;
#[allow(unused)]
pub const CSR_MHPMCOUNTER3H: u16 = 0xb83;
#[allow(unused)]
pub const CSR_MHPMCOUNTER4H: u16 = 0xb84;
#[allow(unused)]
pub const CSR_MHPMCOUNTER5H: u16 = 0xb85;
#[allow(unused)]
pub const CSR_MHPMCOUNTER6H: u16 = 0xb86;
#[allow(unused)]
pub const CSR_MHPMCOUNTER7H: u16 = 0xb87;
#[allow(unused)]
pub const CSR_MHPMCOUNTER8H: u16 = 0xb88;
#[allow(unused)]
pub const CSR_MHPMCOUNTER9H: u16 = 0xb89;
#[allow(unused)]
pub const CSR_MHPMCOUNTER10H: u16 = 0xb8a;
#[allow(unused)]
pub const CSR_MHPMCOUNTER11H: u16 = 0xb8b;
#[allow(unused)]
pub const CSR_MHPMCOUNTER12H: u16 = 0xb8c;
#[allow(unused)]
pub const CSR_MHPMCOUNTER13H: u16 = 0xb8d;
#[allow(unused)]
pub const CSR_MHPMCOUNTER14H: u16 = 0xb8e;
#[allow(unused)]
pub const CSR_MHPMCOUNTER15H: u16 = 0xb8f;
#[allow(unused)]
pub const CSR_MHPMCOUNTER16H: u16 = 0xb90;
#[allow(unused)]
pub const CSR_MHPMCOUNTER17H: u16 = 0xb91;
#[allow(unused)]
pub const CSR_MHPMCOUNTER18H: u16 = 0xb92;
#[allow(unused)]
pub const CSR_MHPMCOUNTER19H: u16 = 0xb93;
#[allow(unused)]
pub const CSR_MHPMCOUNTER20H: u16 = 0xb94;
#[allow(unused)]
pub const CSR_MHPMCOUNTER21H: u16 = 0xb95;
#[allow(unused)]
pub const CSR_MHPMCOUNTER22H: u16 = 0xb96;
#[allow(unused)]
pub const CSR_MHPMCOUNTER23H: u16 = 0xb97;
#[allow(unused)]
pub const CSR_MHPMCOUNTER24H: u16 = 0xb98;
#[allow(unused)]
pub const CSR_MHPMCOUNTER25H: u16 = 0xb99;
#[allow(unused)]
pub const CSR_MHPMCOUNTER26H: u16 = 0xb9a;
#[allow(unused)]
pub const CSR_MHPMCOUNTER27H: u16 = 0xb9b;
#[allow(unused)]
pub const CSR_MHPMCOUNTER28H: u16 = 0xb9c;
#[allow(unused)]
pub const CSR_MHPMCOUNTER29H: u16 = 0xb9d;
#[allow(unused)]
pub const CSR_MHPMCOUNTER30H: u16 = 0xb9e;
#[allow(unused)]
pub const CSR_MHPMCOUNTER31H: u16 = 0xb9f;
