name: Compile check
on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # All generated code should be running on stable now, MRSV is 1.59.0
        target: [riscv32i-unknown-none-elf, riscv32imc-unknown-none-elf, riscv32imac-unknown-none-elf, riscv64imac-unknown-none-elf, riscv64gc-unknown-none-elf]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check
          args: --verbose --target ${{ matrix.target }}
