name: Doc build check
on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
